## Akutt vertigo {#sec-akutt}

Akutt, nyoppstått vertigo krever øyeblikkelig hjelp. Det er viktig å avklare om det foreligger en alvorlig tilgrunnliggende sykdom. Synkope, nærsynkope, palpitasjoner, hjerterytmeforstyrrelser, brystsmerter og dyspné er momenter som kan tale for kardiogen årsak. Hodepine og sentralnervøse symptomer som sløret bevissthet, talevansker, ataksi, pareser, refleksasymmetri og sensibilitetsutfall kan tale for cerebrovaskulær årsak.

Generelle risikofaktorer for cerebrovaskulær sykdom bør også tas med i betrakning, som høy alder, hypertensjon, kjent hjertesykdom, diabetes og tidligere slag eller TIA. Ved isolert vertigo som er ledsaget av ustøhet, kvalme, brekninger eller hørselssymptomer, mistenkes først og fremst sykdom i det indre øret, som [vestibularisnevritt](#sec-vestibularisnevritt). Ikke desto mindre kan slik isolert vertigo også ses ved sentralnervøse tilstander inkludert [lillehjerneinfarkt](#sec-lillehjerneinfarkt). Å skille mellom et [lillehjerneinfarkt](#sec-lillehjerneinfarkt) og [vestibularisnevritt](#sec-vestibularisnevritt) er utfordrende klinisk. Fire kliniske kriterier ([HINTS+](#sec-HINTS)) har vist seg å ha høyere diagnostisk sensitivitet for sentrale lesjoner enn MR de første 48 timene etter symptomdebut ved akutt vertigo.

[Benign paroksysmal posisjonsvertigo](#sec-bppv) (BPPV) er den vanligste årsaken til akutt vertigo. Diagnosen stilles ved observasjon av karakteristisk nystagmus og vertigo ved Dix-Hallpikes manøver. Pasienten kan behandles umiddelbart, og innleggelse er vanligvis ikke nødvendig.

[Vestibularisnevritt](#sec-vestibularisnevritt) diagnostiseres hovedsakelig ut fra kliniske funn i akuttfasen. Ved uttalte symptomer som er akutte og nyoppståtte og som ikke passer med BPPV, er det ofte mest hensiktsmessig å legge pasienten inn for videre diagnostikk og behandling. Det kan være spesielt utfordrende å skille mellom vestibularisnevritt og lillehjerneinfarkt, som begge kan debutere med akutt vertigo, kvalme, brekninger, falltendens og nystagmus. Patologisk hodeimpulstest taler for perifer årsak.
