# Balansesystemet {#sec-balansesystemet}

Balansesystemet -- også kalt det posturale systemet -- refererer til de ulike systemene i kroppen som gjør det mulig å stå og bevege seg oppreist og som forhindrer fall. Disse funksjonene er komplekse og involverer flere sansesystemer, både det sentrale og perifere nervesystemet, samt hele kroppens bevegelsesapparat.

Det å stå og gå oppreist er så grunnleggende funksjoner, at vi vanligvis ikke tenker mye over dem i det daglige. Kroppen vår håndterer disse oppgavene for oss gjennom ubevisste reflekser der nervesystemet vårt reagerer på sansestimuli og utløser raske, automatiske muskelresponser. Sensorene i balansesystemet er øyne, balanseorganer og mekanoreseptorer i hud, sener og ledd. Effektorene er skjelettmusklene. Lillehjernen gir fleksibilitet gjennom konstant modulering av innkommende og utgående signaler, mens hjernestamme og ryggmarg er viktige reléstasjoner. Som helhet er systemet robust fordi sanseorganene er parede og til en viss grad kan erstatte hverandre, og fordi hjernen hele tiden endrer seg slik at balansesystemets funksjon i mange tilfeller kan gjenopprettes etter en skade.

![Balansesystemet fremstilt forenklet og skjematisk. Hjernen sender motoriske signaler eller kommandoer til ryggmargen, som igjen utløser muskelkontraksjoner som resulterer i endringer i kroppsholdning eller hodestilling. De tre sansesystemene - syn, likevektssans og propriosepsjon - samler inn informasjon om virkningen av bevegelsene og eventuelle eksterne faktorer, og sender tilbakemeldinger til hjernen. Hjernen sammenligner en kopi av sine egne kommandoer (efferenskopi) med resultatene som måles gjennom sansesystemene, og bruker denne informasjonen til å justere sine motoriske signaler for å oppnå ønsket effekt.](images/balansesystemet.png){style="padding:40px;"}
