## Barotraume av øret {#sec-barotraume}

**ICD-10:** Otisk barotraume (T70.0)\
**ICD-11:** Otitic barotrauma (NF04.0)\
**Synonymer:** Barotrauma auris, «øreskvis»\
**Definisjon:** Barotraume er vevskade som skyldes endret omgivelsestrykk. Alle gassfylte hulrom i kroppen kan være utsatt for barotraume.\
**Forekomst:** Barotraume av øret er det vanligste medisinske problemet ved dykking. Blant erfarne sportsdykkere er livstidsprevalens ca. 50 % for barotraume av øret, ca. 5 % for trommehinneruptur og ca. 1 % for labyrintfistel. Andre grupper: Forekomst blant yrkesdykkere synes noe lavere. Lettere barotraume av mellomøret er vanlig ved flyging, særlig hos barn.\
**Etiologi:** Endring i omgivelsestrykk ved dykking eller flyging.\
**Patogenese:** Boyles lov (P · V = k): Gassfylte hulrom i kroppen komprimeres (volumet reduseres) ved økt omgivelsestrykk slik at trykk ganger volum er konstant, mens væsker og faste stoffer ikke kan komprimeres. Barotraume av øregang: Skyldes tettsittende hette under nedstigning slik at vann ikke kan trenge inn i øregangen. Valsalvas manøver forverrer problemet og kan medføre trommehinneruptur. Barotraume av mellomøre: Skyldes manglende utligning av mellomøretrykk via øretrompet. Ved nedstigning lukkes sistnevnte ved 1,2 meters dybde slik at utligning krever kraftig trykk (Valsalva). Strekk på trommehinne og slimhinne i mellomøret fører til varierende grad av skade med otalgi, blødning, hematotympanon, ruptur, mekanisk hørselstap. Barotraume av det indre øret: Perilymfefistel oftest forårsaket av ruptur av membranen i det runde vinduet. Dette gir vertigo og nevrogent hørselstap [@Klingmann2007].\
**Anamnese:** Akutt debut under nedstigning (vanligst) eller oppstigning. Otalgi, hørselstap, øresus. Eventuelt blødning fra øret. Barotraume av det indre øret: Vertigo i tillegg til de øvrige symptomene. Se: Perilymfatisk fistel.\
**Kliniske funn:** Barotraume av øregang: Rubor og hematom i øregang og trommehinne. Eventuelt trommehinneruptur. Mekanisk hørselstap: Webers prøve lateraliserer til det syke øret. Barotraume av mellomøret: Hematom i trommehinne, hematotympanon, evt. ruptur og blødning i øregang. Mekanisk hørselstap (Webers prøve lateraliserer mot det syke øret). Barotraume av det indre øret: Nevrogent hørselstap. I akuttfasen spontannystagmus og patologisk hodeimpulstest. Eventuelt positiv fistelprøve. Se: Perilymfatisk fistel.\
**Supplerende undersøkelser:** Audiometri: Mekanisk hørselstap ved barotraume av øregang og mellomøre. Nevrogent hørselstap ved skade av det indre øret. Kalorisk prøve:Kan vise kanalparese ved skade av det indre øret. Annet: Bakteriedyrkning ved purulent sekret.\
**Diagnose:** Barotraume av øregang og mellomøre diagnostiseres ut fra symptomdebut med otalgi under dykk og påvist skade ved otomikroskopi (hematom, ruptur, blødning). Barotraume av det indre øret mistenkes ved akutt oppstått nevrogent hørselstap og vertigo under dykk. Diagnosen kan styrkes ved positiv fistelprøve eller eksplorativ tympanotomi.\
**Ansvarsfordeling:** Allmennleger bør kunne diagnostisere og behandle barotraume av øregang og mellomøre. Isolerte trommehinneskader tilheles vanligvis spontant. Ved manglende tilheling eller komplikasjoner som vertigo, nevrogent hørselstap eller bestående mekanisk hørselstap skal pasienten henvises til øre-nese-halslege.\
**Mål for behandling:** Behandle eventuelle komplikasjoner. Forebygge nye episoder.\
**Behandling:** Konservativ behandling er oftest tilstrekkelig da de fleste trommehinne- og mellomøreskader tilheles spontant. Otitt med sekresjon: Opprensking, evt. antibiotika. Bestående trommehinneperforasjon: Evt. operasjon (myringoplastikk). Perilymfefistel: Se eget kapittel. Forebygging: Unngå dykk ved forkjølelse eller utligningsproblemer. Opplæring i riktig teknikk for utligning [@Molvær2002].\
**Prognose:** Prognosen ved isolert trykkskade av trommehinne/mellomøre er svært god. Det er rapportert at gjentatte skader kan føre til bestående hørselstap. Ved skade av det indre øret forekommer bestående hørselstap, og i noen tilfeller kronisk svimmelhet.
