## Benign paroksysmal posisjonsvertigo {#sec-bppv}

**ICD-10:** Godartet paroksysmal vertigo (H81.1)\
**ICD-11:** Benign paroxysmal positional vertigo (AB31.2)\
**Synonymer:** Godartet paroksysmal stillingssvimmelhet, «krystallsyke», BPPV\
**Forekomst:** Ettårsprevalens 1,6 % i Tyskland. Tilsvarer ca. 80 000 nordmenn i løpet av ett år. Forekomst øker med alder. Sjelden blant barn.\
**Etiologi:** Oftest idiopatisk. Hodetraume. Disponerende faktorer: Høy alder, hyppigere hos kvinner, menopause, vitamin D-mangel, osteoporose. Sjeldne årsaker: Vibrasjon ved tannboring. Visse typer idrett.\
**Patogenese:** Antatt canalolithiasis (vanligst) eller cupulolithiasis. Canalolithiasis er en dynamisk feilfunksjon forårsaket av løse partikler i en av buegangene i det indre øret. Partiklene antas å være otolitter fra macula utriculi. Cupulolithiasis er en statisk feilfunksjon som følge av partikler festet til cupula. Canalolithiasis i bakre buegang er vanligst (ca. 80 %) deretter canalolithiasis og cupulolithiasis i laterale buegang.\
**Anamnese:** *Debut:* Oftest hyperakutt mens pasienten befinner seg i sengen. Utløst av hodebevegelse. *Tidsforløp:* Kortvarige, kraftige anfall av sekunders varighet. Uvelhet kan vare lengre. Tendens til spontan bedring (60 %) i løpet av uker. Tendens til residiv (opp til 50 % i løpet av flere år). *Svimmelhetens karakter:* Rotatorisk (oftest) eller nautisk vertigo. *Utløsende faktorer:* Anfallene utløses alltid av en hodebevegelse, typisk når pasienten legger seg ned i sengen, snur seg i sengen, setter seg opp, legger hodet bakover eller bøyer seg framover. *Ledsagende symptomer:* Lettere kvalme (vanlig), brekninger (uvanlig), lettere ustøhet (vanlig), angst (vanlig), fobi mot bestemte hodebevegelser (vanlig). Sistnevnte kan vedvare etter at sykdommen er opphørt.\
**Kliniske funn:** Karakteristisk posisjonsnystagmus og -vertigo. Uspesifikk ustøhet. Øvrige undersøkelser er vanligvis normale.\
**Supplerende undersøkelser:** Vanligvis normale og derfor unødvendig i typiske tilfeller. CT eller MR vurderes for å utelukke bl.a. tumor i bakre skallegrop ved atypisk klinikk.\
**Diagnose:** Tentativ diagnose kan stilles basert på karakteristisk anamnese dersom pasienten er i asymptomatisk fase. I symptomatisk fase stilles diagnosen etter følgende kriterier [@VonBrevern2015]:

::: diagnose
*Canalithiasis bakre buegang (PCAN):*

A.  Gjentatte anfall av posisjonsvertigo eller -svimmelhet framprovosert av å legge seg ned eller snu seg i liggende stilling
B.  Anfallsvarighet *\< 1 minutt*
C.  Posisjonsnystagmus utløses etter en latenstid på ett eller få sekunder av Dix-Hallpikes manøver eller sideleie-manøver (Semonts diagnostiske manøver). Nystagmusretningen er en kombinasjon av torsjon der øynenes øvre pol slår mot det nederste øret og vertikal nystagmus som slår oppover (mot pannen). Nystagmus varer vanligvis *\< 1 minutt*.
D.  Ikke forklart av annen sykdom

*Canalithiasis horisontale buegang (HCAN):*

A.  Gjentatte anfall av posisjonsvertigo eller -svimmelhet framprovosert av å legge seg ned eller snu seg i liggende stilling
B.  Anfallsvarighet *\< 1 minutt*
C.  Posisjonsnystagmus utløses etter kort eller ingen latenstid av liggende rulletest. Nystagmusretningen er horisontal, og øyet slår mot det *nederste* øret enten hodet dreies mot høyre eller venstre (geotrop nystagmus som skifter retning). Nystagmus varer *\< 1 minutt*.
D.  Ikke forklart av annen sykdom

*Cupulolithiasis horisontale buegang (HCUP):*

A.  Gjentatte anfall av posisjonsvertigo eller -svimmelhet framprovosert av å legge seg ned eller snu seg i liggende stilling
B.  Posisjonsnystagmus utløses etter kort eller ingen latenstid av liggende rulletest. Nystagmusretningen er horisontal og øyet slår mot det *øverste* øret enten hodet dreies mot høyre eller venstre (apogeotrop nystagmus som skifter retning). Nystagmus varer *\> 1 minutt*.
C.  Ikke forklart av annen sykdom

*Canalolithiasis fremre buegang (ACAN):*

A.  Gjentatte anfall av posisjonsvertigo eller -svimmelhet framprovosert av å legge seg ned eller snu seg i liggende stilling
B.  Anfallsvarighet *\< 1 minutt*
C.  Posisjonsnystagmus utløses umiddelbart eller etter en latenstid på ett til noen få sekunder av Dix-Hallpikes manøver til en eller begge sider eller i liggende stilling med hodet hengende rett bakover. Nystagmusretningen er hovedsakelig vertikal nedadslående og varer i *\< 1 minutt*.
D.  Ikke forklart av annen sykdom
:::

**Differensialdiagnoser:** Vestibularisnevritt gir spontannystagmus (i ro). Ortostatisk hypotensjon gir ikke svimmelhet i sengeleie. Kriteriene for BPPV i fremre buegang er foreløpig omdiskuterte. Nedadslående nystagmus kan ses ved sentralnervøse sykdommer, og dersom symptomer og funn ikke er typiske for BPPV anbefales lav terskel for å rekvirere MR caput.\
**Ansvarsfordeling:** Tilstanden er så vanlig at primærleger bør kunne Dix-Hallpikes manøver og Epleys manøver for diagnostikk og behandling av BPPV. Kompliserte eller atypiske tilfeller henvises til øre-nese-halsspesialist.\
**Mål for behandling:** Å forkorte sykdomsforløpet. Forebygge utvikling av kronisk svimmelhet. Oppnå best mulig funksjon.\
**Behandling:** Behandling starter så snart diagnosen er stilt. Den vanligste formen (canallithiasis bakre buegang) behandles normalt med Epleys eller Semonts manøver. Canalolithisis i laterale buegang kan behandles med 270 graders rotasjon mot frisk side i liggende stilling (barbeque-manøver). Cupulolithiasis kan eventuelt behandles med vibrasjon mot processus mastoideus på syk side og vil da i noen tilfeller kunne konverteres til canalolithiasis som behandles med barbeque-manøver. Canalolithiasis i fremre buegang kan behandles med Epley-manøver eller Yacovino-manøver. Kirurgisk okklusjon av den affiserte buegangen er mulig, men svært sjelden nødvendig.\
**Prognose:** Spontanforløpet er oftest gunstig, men kan være langvarig. Uten behandling vil omkring 30 % ha symptomer i mer enn tre måneder. 70-90 % av pasientene med den vanligste formen for BPPV blir asymptomatiske etter en enkel behandlingssesjon med Epley-manøver. De fleste blir asymptomatiske ved gjentatt behandling eller ved hjemmeøvelser, men et lite mindretall kan ha vedvarende eller hyppig residiverende plager. Tilbakefall er vanlig (opp til 50 % over flere år), men behandling er vanligvis effektiv også ved residiv.

Epley-manøver på benk:\
[Epleys manøver på benk mot venstre](https://vimeo.com/805533323)

Hjemmeøvelser:\
[Epleys manøver mot høyre](https://vimeo.com/805534175)\
[Epleys manøver mot venstre](https://vimeo.com/805533438)
