# Dix-Hallpikes manøver

Dix-Hallpikes manøver brukes for å påvise sykdommen benign paroksysmal posisjonsvertigo (BPPV). Den skal ikke brukes på pasienter med spontannystagmus og akutt vestibulært syndrom, som sjelden skyldes BPPV og der første prioritet er å diagnostisere og behandle hjerneslag.

Undersøkelsen starter med pasienten sittende på benk eller i seng. Dersom seng benyttes, er det fordel om hodegjerdet kan tas av, slik at hodet kan komme utenfor kanten. La pasienten sitte oppreist i minst 5 minutter (helst 30 minutter) før undersøkelsen for å unngå falsk negativt resultat. Sjekk at pasienten ikke har spontannystagmus etter dette.

Pasienten dreier hodet 45 grader til siden. Dersom man på forhånd kjenner den syke siden, begynner man med denne. Pasienten legger seg ned på rygg med hodet utenfor benkekanten og nakken ekstendert ca. 15 grader. Øynene observeres. Eventuell vertigo og nystagmus noteres. Pasienten setter seg opp igjen, eventuell vertigo og nystagmus noteres. Manøveren gjentas med hodet 45 grader til den andre siden. (Posisjonsnystagmus ved BPPV vil i typiske tilfeller være kraftig nok til å observeres uten Bartels' brille.) Se video av Dix-Hallpikes manøver på [https://vimeo.com/257039516](#0){.uri}.