## Generelle prinsipper {#sec-behandling}

Behandlingen av de enkelte sykdommene er omtalt i diagnosekapitlene. Noen generelle prinsipper er imidlertid uavhengige av diagnose.

Svimmelhet er et subjektivt symptom som ofte er til mye større bekymring og plage for pasienten enn alvoret i den tilgrunnliggende tilstanden skulle tilsi. Vi vet at svimmelhet ofte forringer pasientenes livskvalitet i like stor grad som livstruende sykdommer som kreft og nyresvikt. Det første trinnet i behandlingen er å ta de subjektive symptomene på alvor. Dette innebærer en grundig anamnese der symptombildet kartlegges og valideres av legen uavhengig av om det umiddelbart melder seg en somatisk diagnose eller ikke. Bagatellisering av subjektive plager eller vage hentydninger til at det kan være psykisk betinget fører til at man får pasienten imot seg fra første stund. Dersom pasienten presenterer klare tegn til psykisk sykdom, skal dette selvfølgelig tas på alvor.

Neste trinn i behandlingen er å formidle trygghet. Dette er selvfølgelig enklest når man har kommet fram til en klar diagnose. De fleste pasienter opplever stor lettelse ved å få en diagnose som bekrefter deres subjektive opplevelse. Det er imidlertid også fullt mulig å formidle trygghet uten en sikker diagnose. Dette handler stort sett om å legge opp et klart løp for eventuell videre utredning, samt å vektlegge om man har klart å utelukke alvorlig sykdom eller funksjonsforstyrrelse. Et viktig moment i utredningen er å avklare om det er noe til hinder for at pasienten kan være i fysisk aktivitet og trene. Trening spiller en viktig rolle i behandlingen av de fleste årsaker til svimmelhet.

Utredningen kan ta tid, særlig dersom man vurderer det slik at det er behov for billeddiagnostikk eller undersøkelse hos ulike spesialister. I forløpet av utredningen kan pasienten oppleve mye usikkerhet. Usikkerhet og svimmelhet har en tendens til å forsterke hverandre. Mange utvikler en unormal oppmerksomhet omkring sin balansefunksjon og blir overfølsom for normale signaler fra kroppen i forbindelse med hodebevegelser og synsinntrykk. Dette fører til bekymring, uvelhet og utmattelse. Noen blir fysisk inaktive og isolerer seg.

Det er viktig å fange opp tidlige tegn til at et problem er i ferd med å bli kronisk. Svimmelhet som varer i mer enn tre måneder er et varsku. Trening og fysisk aktivitet spiller antakelig en nøkkelrolle for å hindre utvikling av kronisk svimmelhet. Spesielle treningsprogrammer for avspenning og vestibulær rehabilitering, inkludert Tai-chi, har dokumentert effekt ved mange årsaker til svimmelhet. Henvisning til fysikalsk behandling bør vurderes tidlig i sykdomsforløpet. Behandlingen består hovedsakelig av egentrening og egenaktivitet. Hvor mye veiledning og oppfølgning som kreves, varierer fra pasient til pasient. Sedativa som f.eks. proklorperazin hjelper sjelden på sikt, og fører ofte til redusert balansefunksjon, særlig hos eldre.

Ved kronisk subjektiv svimmelhet uten objektive funn, er henvisning til psykiater sjelden indisert med mindre det foreligger klare symptomer på psykisk sykdom og pasienten er motivert. Dersom slike symptomer ikke er til stede, men pasienten likevel opplever svimmelhet som er klart situasjonsbetinget (se fobisk postural vertigo), vil en grundig forklaring av symptomene og de fremprovoserende faktorene kunne være til hjelp, i tillegg til treningsprogram med gradvis større eksponering for de svimmelhetsfremkallende situasjonene.
