# Hodeimpulstest {#sec-hodeimpulstest}

Hodeimpulstest er en enkel, klinisk undersøkelse av den vestibulo-okulære refleksen. Utført og tolket riktig, har den høy sensitivitet og spesifisitet for perifere vestibulære lesjoner i akuttfasen. Den inngår også i HINTS^+^-kriteriene.

Sitt ansikt til ansikt med pasienten i samme øyenhøyde og nær nok til at du kan holde pasientents hode stabilt mellom hendene. Informer om at du kommer til å bevege pasientens hode fra side til side med små, men svært raske bevegelser fra side til side. Demonstrer størrelsen på bevegelsen du skal gjøre gjennom å bevege hodet til pasienten ca 10 grader mot høyre og venstre med rolige, jevne bevegelser. Det er viktig at pasienten slapper av i nakken og verken stritter imot eller forsøker å hjelpe til med bevegelsene. Det er også viktig at pasienten holder øynene åpne og festet på ditt øye.

Når du og pasienten er klar, dreier du pasientens hode med en liten, men svært hurtig bevegelse til siden mens du observerer øynene til pasienten. Forsøk bevegelser både mot høyre og mot venstre. Retningen og tidspunktet skal være mest mulig uforutsigbare for pasienten.

Normalt skal de raske hodebevegelsene kompenseres av like raske og motsatt rettede øyebevegelser slik at pasienten hele tiden ser inn i ditt øye. Ved en unilateral parese, vil dette gå bra så lenge de raske hodebevegelsene går til den friske siden. Når hodet beveges mot den syke siden, vil pasientens øyne følge med hodet ut til siden. Etter brøkdelen av et sekund oppdager pasienten dette og flytter blikket tilbake på undersøkeren. Det er denne hurtige korreksjonsbevegelsen (sakkaden) som avslører paresen. Hodeimpulstesten kan også brukes til å påvise bilateral vestibulær parese. Se video på <https://vimeo.com/327010752>.
