## Kronisk svimmelhet {#sec-kronisk}

Kronisk svimmelhet har i mange tilfeller akutt debut, og det er ofte mulig å påvise en eller flere tilgrunnliggende organiske sykdommer. Det er imidlertid karakteristisk at den organiske sykdommen ikke kan forklare alle trekkene i sykdomsbildet.

Noen pasienter utvikler en subjektiv følelse av ubalanse uten at noen objektiv balanseforstyrrelse kan påvises. Korte vertigoanfall utløses av synsinntrykk eller sosiale situasjoner. Anfallene er ofte, men ikke alltid ledsaget av angst. Et mindretall av pasientene har panikklidelse eller agorafobi. Et karakteristisk trekk er at pasienten forsøker å unngå de utløsende situasjonene og etter hvert blir hemmet forhold til normal fysisk og sosial aktivitet.

En beslektet tilstand, kalt kronisk subjektiv svimmelhet, defineres som vedvarende (≥ 3 måneder) følelse av svimmelhet og subjektiv ubalanse med overfølsomhet for egne bevegelser og forverring av symptomene i situasjoner med komplekse visuelle stimuli og uten objektive funn som kan forklare symptomene. Selv om det ofte foreligger tilgrunnliggende psykogene mekanismer, er disse foreløpig ufullstendig beskrevet.

En gruppe pasienter opplever vedvarende gyngende fornemmelse etter å ha vært utsatt for passive bevegelser, for eksempel ved reise med båt, buss, tog mv. Noen får i tillegg spontane episoder. Det er karakteristisk at pasienten føler lettelse når de utsetter seg for de samme bevegelsene igjen. Tilstanden er uvanlig og kalles i internasjonal litteratur [mal de debarquement](#sec-landgangssyndrom). Vi har valgt å bruke betegnelsen [landgangssyndrom](#sec-landgangssyndrom). Den er omtalt i eget diagnosekapittel.

Dette er kun noen eksempler på de funksjonelle mekanismene som kan inntre når svimmelhet varer i lang tid. Det er primært viktig å avklare om det foreligger organisk sykdom som kan behandles. De mest aktuelle diagnosene er omtalt i kapitlene om anamnese og klinisk undersøkelse. Kapittelet om generell behandling av svimmelhet tar også for seg behandlingen av pasienter med svimmelhet uten diagnose. Ofte krever langvarig svimmelhet langsiktig oppfølgning og behandling uavhengig av tilgrunnliggende årsak. Det er viktig at pasienten føler at svimmelhetsopplevelsen blir forstått, samtidig som behandlingen ofte retter seg inn mot andre aspekter ved sykdomsbildet, for eksempel å oppnå bedre funksjonsnivå.
