## Labyrintitt {#sec-labyrintitt}

**ICD-10**: Labyrintitt (H83.0)\
**ICD-11:** Labyrinthitis (AB30.1)\
**Definisjon:** Labyrintitt er en samlebetegnelse på ulike betennelsestilstander i det indre øret som medfører tap av cochleovestibulær funksjon. Labyrintitt har også vært brukt om idiopatiske tilstander med samme kliniske manifestasjoner. **Synonymer**: Eng. Autoimmune inner ear disease (autoimmun labyrintitt). Suppurativ labyrintitt (bakteriell labyrintitt). **Forekomst:** Eksakt forekomst er ukjent. Klinisk labyrintitt er uvanlig, men muligens underdiagnostisert.\
**Etiologi:** Viral eller bakteriell infeksjon, steril inflammasjon av toksisk, traumatisk eller autoimmun årsak [@Strum2020].\
**Patogenese:** Labyrintitt er en inflammasjon i det indre øret som medfører vertigo, hørselstap og tinnitus. Mekanismene varierer: Bakteriell spredning fra mellomøre eller hjernehinner (mastoiditt, kolesteatom, meningitt). Viral reaktivering av nevrotrope virus (herpes simplex, varicella zoster = herpes zoster oticus = Ramsay-Hunt syndrom). Sjeldne infeksjoner med hematogen spredning (borrelia, syfilis, tuberkulose). Autoimmun inflammasjon (Cogans syndrom, systemisk lupus erythematosus, granulomatøs polyangitt mv). Påvirkning fra bakterielle toksiner i mellomøret (serøs labyrintitt).\
**Anamnese:** *Debut:* Akutt (oftest) eller hyperakutt. Noen ganger utløst av bakteriell otitt med eller uten cholesteatom eller av meningitt. Noen ganger assosiert med annen øvre luftveisinfeksjon (\< 50 %) eller sekundært til autoimmun sykdom. *Tidsforløp:* I akuttfasen kontinuerlig vertigo etterfulgt av gradvis bedring over uker til måneder. Kortvarig økning av symptomer relatert til bevegelse og fysisk aktivitet. Serøs labyrintitt har ofte mer kortvarig forløp. Hørselstap kan være permanent. *Svimmelhetens karakter:*Rotatorisk (oftest) eller nautisk vertigo. *Utløsende faktorer:* Se Debut og Tidsforløp. *Ledsagende symptomer:* Nesten alltid kvalme, ofte brekninger. Hørselstap. Tinnitus. Falltendens. Ved bakteriell labyrintitt: Feber, otalgi, redusert allmenntilstand. Facialisparese (sjelden). Ved meningitt: Nakkestivhet, bevissthetstap. Andre hjernenerveutfall.\
**Kliniske funn:** *Paretisk labyrintitt:* Webers prøve lateraliserer og spontannystagmus slår mot det friske øret. Nevrogent hørselstap. Falltendens til syk side. Patologisk hodeimpulstest mot syk side. Otitt. Vesikler i øregang. Nakkestivhet. Bevissthetstap. Funn forenlig med revmatisk eller autoimmun sykdom i andre systemer. *Irritativ labyrintitt:* Webers prøve lateraliserer og spontannystagmus slår mot det syke øret. Mekanisk hørselstap. Falltendens. Otitt.\
**Supplerende undersøkelser:** *Audiometri:* Nevrogent eller mekanisk hørselstap. *Kalorisk prøve:*Kanalparese ved paretisk labyrintitt. *CT:* Abscess, kolesteatom, bendestruksjon, labyrintfistel, meningitt, sinusvenetrombose. *MR:* Indisert bl.a. for å utelukke vestibulært schwannom.\
**Diagnose:** Labyrintitt har mange årsaker, og diagnostiske kriterier avhenger av antatt etiologi. En klinisk, generisk diagnose vil i mange tilfeller baseres på følgende kriterier (A-C oppfylt) uavhengig av etiologi:\

::: diagnose
A.  Akutt vertigo med spontannystagmus
B.  Minst ett av følgende to funn
    1.  Nevrogent hørselstap bekreftet ved audiometri
    2.  Otitt i det aktuelle øret påvist ved otoskopi
C.  Andre årsaker ekskludert
:::

**Differensialdiagnoser:** Menières sykdom, vestibulært schwannom, perilymfatisk fistel, nevrologisk trykkfallsyke, ACIA-infarkt, blødning i labyrinten, tinningbensfraktur, commotio labyrinthi.\
**Ansvarsfordeling:** Akutte tilfeller skal vanligvis innlegges i sykehus for å verifisere diagnosen, behandle evt alvorlig tilgrunnliggende infeksjon og utelukke bl.a. ACIA-infarkt.\
**Mål for behandling:** Forebygge og behandle eventuell livstruende bakteriell infeksjon. Forebygge komplikasjoner i form av permanent hørselstap og kronisk svimmelhet. Lindre symptomer i akuttfasen. Forkorte sykdomsforløp.\
**Behandling:** I akuttfasen: Behandle eventuell tilgrunnliggende bakterieinfeksjon med antibiotika og eventuelt kirurgisk sanering av infeksjonsfokus i tinningben. Behandle eventuell herpes zoster oticus med valacyclovir og kortikosteroid. Behandle eventuell autoimmun eller annen viral labyrintitt med kortikosteroid. Informere og berolige pasienten for å dempe angst, lindre symptomene ved sengeleie og ro. Eventuelt antiemetika, f.eks. proklorperazin 25 mg supp. I kompensasjonsfasen (uker til måneder): Tidligst mulig seponering av sedativa/proklorperazin og mobilisering. Noe økt svimmelhet og kvalme må tolereres. Hyppige pauser, hvile og søvn er viktig. Oppfølgning av fysioterapeut/ balanseterapeut med målrettet trening er sterkt ønskelig.\
**Prognose:** Irritativ labyrintitt: God prognose mht hørsel og balanse. Paretisk labyrintitt:Varierende og ofte bestående hørselstap. Ved bakteriell labyrintitt vanligvis døvt øre. Noe bedre prognose ved viral og autoimmun labyrintitt. Et flertall av pasientene får tilnærmet normal balanse. Noen utvikler kronisk svimmelhet. Prognosen for eventuell facialisparese ved Ramsay-Hunt-syndrom er god, men noe dårligere enn ved Bells parese.
