## Lillehjerneinfarkt {#sec-lillehjerneinfarkt}

**ICD-10:** Hjerneinfarkt forårsaket av uspesifisert okklusjon eller stenose i hjernearterier (I63.5)\
**ICD-11:** Cerebral ischaemic stroke (8B11)\
**Merknad:** Lillehjerneinfarkt er her nevnt fordi tilstanden representerer en viktig differensialdiagnose til bl.a. vestibularisnevritt. Kapittelet gir kun en kort omtale av temaet. Andre lesjoner -- f.eks. blødning, infarkt eller MS -- som rammer sentrale vestibulære strukturer i hjernestammen og lillehjernen, kan gi lignende symptombilde.\
**Forekomst:** Lillehjerneinfarkter utgjør ca. 1,5 % av hjerneslag. Av 14 500 årlige hjerneslag i Norge, vil altså ca. 220 være lillehjerneinfarkter.\
**Etiologi:** Viktige cerebrovaskulære risikofaktorer er bl.a. høy alder, hypertensjon, diabetes, hjertesykdom og tidligere cerebrovaskulær sykdom.\
**Patogenese:** Avhengig av lokalisasjon vil lillehjerneinfarkter kunne gi ulike symptomer. Det er særlig infarkter i det bakre gebetet (a. cerebelli inferior posterior = ACIP) som i noen tilfeller gir isolert vertigo med kvalme, brekninger, falltendens og nystagmus [@Kase1993]. Dette skyldes opphør av signaler fra lobus flocculonodularis til den ipsilaterale vestibulariskjernen. Infarkter i øvre og fremre gebeter (a. cerebelli superior = ACS og a. cerebelli inferior anterior = ACIA) vil kunne gi et bilde som er mer preget av ataksi i ekstremitetene. Store lillehjerneinfarkter, særlig de som omfatter hele ACIP-området, har en tendens til å gi ødemutvikling som av og til kan være livstruende på grunn av avklemming av aqueductus Sylvii, hydrocephalus og herniering. Et flertall av ACIP-infarktene er imidlertid partielle, og det er da liten masseeffekt.\
**Anamnese:** Her omtales kun ACIP-infarkter, som debuterer akutt med vertigo (78 %), hodepine (64 %), falltendens (75 %), kvalme og brekninger (61 %). Det kan være få andre symptomer, men sløret bevissthet er et faresymptom som indikerer trykkutvikling. Hjernenerveutfall og langbanesymptomer kan indikere multiple infarktområder.\
**Kliniske funn:** Ved ACIP-infarkter er nystagmus vanlig (75 %). Nystagmus går oftest mot syk side, men dette kan variere. Falltendens er også vanligvis mot syk side. Ataksi i ekstremitetene forligger i omtrent halvparten av tilfellene ved ACIP-infarkt, men er hyppigere ved ACS-infarkter. Lateralt medullært syndrom foreligger ved ca. 1 av 3 ACIP-infarkter.\
**Diagnose:** Ved klinisk mistanke er CT eller MR med diffusjonsvekting indisert.
