## Skader som årsak til svimmelhet {#sec-skader}

Svimmelhet kan av og til oppstå som følge av skader, forgiftninger eller andre ytre årsaker. Måneder og år etter skaden kan det bli spørsmål om vurdering av medisinsk invaliditet, menerstatning og om årsakssammenhengen mellom den ytre skaden og kroniske symptomer. Noen sentrale momenter er om det foreligger objektive funn som bekrefter skaden og om det er sannsynlig årsakssammenheng mellom skaden og funnene/symptomene.

Denne vurderingen er ofte vanskelig, og gode opplysninger fra legen som undersøkte pasienten i akuttfasen kan få stor betydning. Dersom svimmelhet inngår i symptombildet, bør det tas opp en strukturert vertigoanamnese og gjøres en klinisk undersøkelse som innbefatter vurdering av nystagmus. Noen aktuelle diagnoser i forhold til svimmelhet og vertigo er omtalt i kapitlene om [tinningbensfraktur](#sec-tinningbensfraktur), [commotio labyrinthi](#sec-commotio_labyrinthi), [benign paroksysmal posisjonsvertigo](#sec-bppv), [labyrintfistel](#sec-perilymfatisk_fistel), [barotraume](#sec-barotraume), [trykkfallsyke](#sec-trykkfallsyke) og [bilateral vestibulopati](#sec-bilateral).
