## Svimmelhet og fall hos eldre {#sec-eldre}

Svimmelhet, synkoper, ustøhet og fall er vanlig blant eldre. Her nevnes noen av de viktigste årsakene og aktuelle tiltak.

Aldring medfører redusert muskelkraft, holdningsendringer og stive ledd. Redusert bevegelighet og opplevde fall medfører frykt for å falle, som i sin tur ofte gir dårligere balanse. Fysisk inaktivitet bidrar til å forverre problemene. Trening av muskelstyrke og balanse (inkludert Tai-chi) har dokumentert effekt ved balanseproblemer hos eldre.

[Ortostatisk hypotensjon](#sec-ortostatisk) er en av de vanligste årsakene til svimmelhet, synkoper og fall hos eldre. Utredning og behandling er omtalt i eget diagnosekapittel. Alkoholinntak forverrer ortostatismen og er ofte medvirkende til synkoper og fall.

Eldre bruker ofte mange [medikamenter](#sec-medikamenter), og flere av disse kan ha svimmelhet som bivirkning. Dette gjelder særlig medikamenter som forårsaker hypotensjon inkludert blodtrykksmedisiner, diuretika og noen typer antidepressiva. Andre medikamenter forårsaker svimmelhet og bevegelsesforstyrrelser gjennom å virke på sentralnervesystemet. Proklorperazin brukes ofte feilaktig til å behandle kronisk svimmelhet, og kan da medføre ekstrapyramidale bivirkninger, bevegelsesforstyrrelser og ustøhet.

Forebygging av fall inkluderer bruk av personlige hjelpemidler som rullator, krykker og hoftebeskytter. Det er også viktig å fjerne «fallfeller» i hjemmet og montere sikringsutstyr, f.eks. sklisikre matter og håndtak på utsatte steder. Ergoterapeut bør involveres ved anamnestisk falltendens. Fall i institusjoner kan forebygges gjennom god bemanning og hyppig tilsyn når anamnesen tilsier høy fallrisiko.

[Benign paroksysmal posisjonsvertigo](#sec-bppv) er svært vanlig blant eldre. Tilstanden er oftest enkel å diagnostisere og behandle. Dix-Hallpikes manøver er derfor en svært viktig del av utredningen av eldre med svimmelhet. Eldre pasienter har ofte vanskeligere for å gjøre hjemmeøvelser, og kan derfor kreve tettere oppfølgning.

Demens er en vanlig årsak til fall på grunn av mer ukritisk atferd, redusert koordinasjon og balanse. Depresjon er også vanlig hos eldre, og kan medføre svimmelhet og frykt for å falle. God utredning og informasjon til pasienten er viktig for å dempe sykdomsangst.
