## Vestibulær trykkfallsyke {#sec-trykkfallsyke}

**ICD-10:** Trykkfallsyke (T70.3)\
**ICD-11:** Caisson disease (NF04.2)\
**Synonymer:** Dykkersyke og eng. decompression sickness eller caisson disease betegner trykkfallsyke generelt. Uttrykk som «the bends», «the chokes», «the staggers» er upresise, men forekommer fortsatt som betegnelse på trykkfallsyke med organsymptomer fra ledd, lunger og det indre øret.\
**Definisjoner:** *Type I trykkfallsyke:* Leddsmerter og/eller hudsymptomer. *Type II trykkfallsyke:*Organssymptomer (hjerne, ryggmarg, hjerte, lunger, det indre øret). Vestibulær trykkfallsyke (eng. inner ear decompression sickness) er type II trykkfallsyke med vestibulært utfall.\
**Forekomst:** Hos dykkere er livstidsinsidensen av trykkfallsyke 1 per 5000 -- 10000 dykk[@Taylor2003]. Hvor mange av disse som har alvorlig trykkfallsyke (type II) er usikkert og varierer i henhold til kritierier. Vestibulære utfall er i flere studier funnet hos 20-30 % av dykkere med alvorlig trykkfallsyke[@Kennedy1975]. Prevalens av patent foramen ovale er \> 25 % hos voksne.\
**Etiologi:** Dykking. Raskt trykkfall ved flyging. Patent foramen ovale øker risiko for arteriell gassemboli og synes å være en viktig medvirkende faktor ved vestibulær trykkfallsyke.\
**Patogenese:** Raskt trykkfall gjør at gasser som er fysiologisk løst i kroppens vev frigjøres og danner bobler. Dette gjelder hovedsakelig nitrogen ved pusting i luft. Gassbobler forårsaker vevsskade direkte eller fraktes via det venøse kretsløpet til lungene. Ved patent foramen ovale kan boblene komme over i det arterielle kretsløpet og forårsake gassemboli med iskemi og vevsskade bl.a. i det indre øret. Balanseorganet synes å være spesielt utsatt, hørselsskade er noe mer uvanlig.\
**Anamnese:** Her omtales vestibulær trykkfallsyke. *Debut:* Akutt kort tid etter oppstigning fra dykk eller ved flyging, særlig etter dykking. *Svimmelhetens karakter:* Rotatorisk eller nautisk vertigo. *Utløsende faktorer:* Trykkfall forverrer symptomene, umiddelbar rekompresjon kan få symptomene til å opphøre. Fysisk anstrengelse kan føre til at symptomene øker. *Ledsagende symptomer:* Kvalme, brekninger, falltendens. Evt. hørselstap og tinnitus. Andre symptomer på trykkfallsyke type I eller II.\
**Kliniske funn:** *Vestibulær trykkfallsyke:* Spontannystagmus mot frisk side, falltendens mot syk side, patologisk hodeimpulstest mot syk side. *Med cochleære symptomer:* Nedsatt hørsel på syk side. Lateralisering av Webers prøve til frisk side.\
**Supplerende undersøkelser:** *Vestibulær trykkfallsyke:* Kanalparese ved kalorisk prøve. Audiometri er indisert for å utrede eventuell affeksjon av cochlea. Ekko-cor med spørsmål om patent foramen ovale. MR er indisert for å påvise eventuell annen sentral årsak til symptomene.\
**Diagnose:** *Vestibulær trykkfallsyke:* Tilstanden mistenkes ved svimmelhet eller vertigo som oppstår kort tid etter dykk. Nivå kan fastsettes som perifert vestibulært dersom det ikke foreligger åpenbare sentrale utfall samtidig som pasienten har vertigo, kvalme, spontannystagmus og påvist perifer parese (hodeimpulstest og/eller kalorisk prøve). Evt. nevrogent hørselstap taler også for perifer lesjon.\
**Ansvarsfordeling:** Ved mistanke skal pasienten omgående sendes til nærmeste trykkammer for rekompresjon. Videre utredning ved nevrologisk avdeling i samarbeid med øre-nese-halsavdeling.\
**Mål for behandling:** Forkorte sykdomsforløpet. Forebygge permanent hørselstap og kronisk svimmelhet. Forebygge nye skader.\
**Behandling:** Ved klinisk mistanke er umiddelbar rekompresjon indisert. Ytterligere behandling kan inkludere balansetrening og opptrening. Vestibulær trykkfallsyke kan innebære fremtidig dykkeforbud, men må vurderes individuelt.\
**Prognose:** Den perifere skaden er ofte permanent til tross for rekompresjon. Prognosen er likevel god på sikt takket være sentral kompensasjon. Lette restsymptomer er vanlig.
