## Vestibularisschwannom {#sec-vestibularisschwannom}

**ICD-10:** Godartet svulst i hjernenerve (D33.3)\
**ICD-11:** Benign neoplasm of cranial nerves (2A02.3)\
**Synonymer:** Akustikusnevrinom. Eng. acoustic neuroma.\
**Forekomst:** Ettårsinsidens 20 : 1 000 000 eller ca. 100 nyoppdagede svulster i Norge per år. Diagnostiseres oftest hos voksne. Hos unge under 20 år kan svulsten skyldes nevrofibromatose type 2.\
**Etiologi:** Oftest ukjent. Nevrofibromatose kan medføre multiple schwannomer med ulik lokalisasjon. Nevrofibromatose type 2 er forårsaket av en delesjon i den lange armen av kromosom 22.\
**Patogenese:** Godartet svulst utgående fra de schwannske celler i nervus vestibularis, som er en del av 8. hjernenerve. Tumor vokser vanligvis fra indre øregang og ut i den cerebellopontine vinkel i bakre skallegrop, og forårsaker symptomer gjennom press mot hørselsnerven, kompromittering av blodforsyningen til det indre øret og, dersom den er større enn 20 mm, trykk mot hjernestamme og tilgrensende hjernenerver.\
**Anamnese:** Vanligste symptomer er gradvis innsettende og progredierende ensidig tinnitus og hørselstap samt ukarakteristisk svimmelhet og ustøhet. Et mindretall av pasientene har akutt innsettende eller fluktuerende hørselssymptomer og vertigoanfall. Trigeminusutfall er mindre vanlig. Facialisparese er meget sjelden, selv om tumor trykker mot nerven.\
**Kliniske funn:** *Vanlige:* Lateralisering av Webers prøve til det friske øret. *Mindre vanlige:* Falltendens. Patologisk hodeimpulstest. Trigeminusutfall (redusert cornearefleks) *Sjeldne:* Facialisparese.\
**Supplerende undersøkelser:** *Rentoneaudiometri:* Ensidig nevrogent hørselstap, oftest i diskant. *Taleaudiometri:* Ofte dårligere enn rentone-resultatet skulle tilsi. *Hjernestammeaudiometri:* Forsinket femte bølge. *Kalorisk prøve:* Kanalparese hvis svulsten utgår fra øvre gren av n. vestibularis (ca. 40 %).\
**Diagnose:** Pasienter med asymmetrisk hørselstap, vertigo og tinnitus uten sikker årsak bør utredes med MR av tinningben og den cerebellopontine vinkel. CT kan vise utvidelse av porus acusticus internus, men har betydelig lavere sensitivitet enn MR. Hjernestammeaudiometri kan indikere retrocochleær lidelse, men MR er påkrevet ved mistanke om VS.\
**Ansvarsfordeling:** Pasienter med asymmetrisk hørselstap og tinnitus av ukjent årsak bør henvises til øre-nese-halsspesialist.\
**Mål for behandling:** Forebygge sekundære skader relatert til tumorvekst. Forebygge og behandle utvikling av kronisk svimmelhet.\
**Behandling:** De minste svulstene vil ofte ikke vokse etter diagnosetidspunktet (ca. 60 %). Behandling er i slike tilfeller ikke vist å gi bedret livskvalitet. Man foretrekker da oftest regelmessige kontroller med MR[@Myrseth2007]. Det anbefales MR-kontroll årlig første 10 år. Hvis svulsten ikke har vokst i løpet av 5-7 år, er risiko for vekst meget liten. *Strålekniv (gammakniv, stereotaktisk strålebehandling):* Foretrukket behandling ved vekst av mindre svulster. *Kirurgi:* Foretrekkes ved større svulster. Ved uttalt eller langvarig svimmelhet er vestibulær rehabilitering i form av egentrening under veiledning av fysioterapeut/balanseterapeut første valg, men kirurgi kan vurderes i enkelttilfeller. Forbehandling med vestibulære øvelser og medikamentell labyrintdestruksjon kan forkorte det postoperative sykdomsforløpet.\
**Prognose:** Avhengig av tumorstørrelse. Permanent hørselstap og øresus må påregnes. *Kirurgi:*Makroskopisk fjerning av tumor hos \~95 %. Effekt på svimmelhet og balanseproblemer i noen tilfeller. *Komplikasjoner assosiert med tumorstørrelse:* facialisparese, trigeminusskade. Postoperativ hodepine, liquorré. Postoperativ meningitt. Dødsfall 0-2 %, oftest knyttet til postoperative hjerte-lunge-komplikasjoner.
